"""
Learning Agent for tracking performance and generating daily reports
"""
import datetime
import os
from typing import Dict, List, Optional
from dataclasses import dataclass
from .config import LearningConfig


@dataclass
class PerformanceMetric:
    """Data class to store performance metrics"""
    timestamp: datetime.datetime
    profit_loss: float
    trades_count: int
    win_rate: float
    total_return: float
    max_drawdown: float


class LearningAgent:
    """Agent that tracks trading performance and generates daily reports"""
    
    def __init__(self, config: LearningConfig):
        self.config = config
        self.performance_history: List[PerformanceMetric] = []
        self.reports_dir = config.reports_directory
        
        # Create reports directory if it doesn't exist
        os.makedirs(self.reports_dir, exist_ok=True)
    
    def record_performance(
        self, 
        profit_loss: float, 
        trades_count: int, 
        win_rate: float, 
        total_return: float, 
        max_drawdown: float
    ):
        """Record a new performance metric entry"""
        metric = PerformanceMetric(
            timestamp=datetime.datetime.now(),
            profit_loss=profit_loss,
            trades_count=trades_count,
            win_rate=win_rate,
            total_return=total_return,
            max_drawdown=max_drawdown
        )
        self.performance_history.append(metric)
        
        # Keep only the last N records to prevent memory overflow
        if len(self.performance_history) > self.config.max_history_records:
            self.performance_history = self.performance_history[-self.config.max_history_records:]
    
    def generate_daily_report(self, target_date: Optional[datetime.date] = None) -> str:
        """Generate a daily performance report in Markdown format"""
        if target_date is None:
            target_date = datetime.date.today()
        
        # Filter metrics for the specific date
        daily_metrics = [
            metric for metric in self.performance_history
            if metric.timestamp.date() == target_date
        ]
        
        if not daily_metrics:
            return self._generate_empty_report(target_date)
        
        # Calculate daily aggregates
        total_pl = sum(m.profit_loss for m in daily_metrics)
        total_trades = sum(m.trades_count for m in daily_metrics)
        avg_win_rate = sum(m.win_rate for m in daily_metrics) / len(daily_metrics) if daily_metrics else 0
        max_total_return = max(m.total_return for m in daily_metrics) if daily_metrics else 0
        max_drawdown = min(m.max_drawdown for m in daily_metrics) if daily_metrics else 0
        
        # Generate report content
        report_content = f"""# Daily Trading Report - {target_date.strftime('%Y-%m-%d')}

## Executive Summary
- Total Profit/Loss: ${total_pl:,.2f}
- Total Trades: {total_trades}
- Average Win Rate: {avg_win_rate:.2f}%
- Maximum Total Return: {max_total_return:.2f}%
- Maximum Drawdown: {max_drawdown:.2f}%

## Performance Details
| Time | P&L | Trades | Win Rate | Return | Drawdown |
|------|-----|--------|----------|--------|----------|
"""
        
        for metric in daily_metrics:
            report_content += (
                f"| {metric.timestamp.strftime('%H:%M')} "
                f"| ${metric.profit_loss:,.2f} "
                f"| {metric.trades_count} "
                f"| {metric.win_rate:.2f}% "
                f"| {metric.total_return:.2f}% "
                f"| {metric.max_drawdown:.2f}% |\n"
            )
        
        # Add insights section
        report_content += "\n## Key Insights\n"
        if daily_metrics:
            best_metric = max(daily_metrics, key=lambda x: x.profit_loss)
            worst_metric = min(daily_metrics, key=lambda x: x.profit_loss)
            
            report_content += f"- Best performing period: {best_metric.timestamp.strftime('%H:%M')} (${best_metric.profit_loss:,.2f})\n"
            report_content += f"- Worst performing period: {worst_metric.timestamp.strftime('%H:%M')} (${worst_metric.profit_loss:,.2f})\n"
        
        # Add recommendations based on performance
        report_content += "\n## Recommendations\n"
        if avg_win_rate < 0.4:
            report_content += "- Win rate is below 40%, consider adjusting strategy\n"
        elif avg_win_rate > 0.6:
            report_content += "- Win rate is strong, maintain current approach\n"
        else:
            report_content += "- Win rate is moderate, monitor closely\n"
            
        if max_drawdown < -0.1:  # More than 10% drawdown
            report_content += "- Significant drawdown detected, risk management review advised\n"
        
        report_content += "\n*Generated by OpenClaw Learning Agent*\n"
        
        return report_content
    
    def _generate_empty_report(self, target_date: datetime.date) -> str:
        """Generate an empty report when no data is available for the date"""
        return f"""# Daily Trading Report - {target_date.strftime('%Y-%m-%d')}

## Executive Summary
No trading activity recorded for this day.

## Performance Details
No data available.

## Key Insights
No insights available due to lack of trading activity.

## Recommendations
No recommendations available.

*Generated by OpenClaw Learning Agent*
"""
    
    def save_daily_report(self, target_date: Optional[datetime.date] = None) -> str:
        """Save the daily report to a file and return the file path"""
        if target_date is None:
            target_date = datetime.date.today()
        
        report_content = self.generate_daily_report(target_date)
        filename = f"daily_report_{target_date.strftime('%Y%m%d')}.md"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        return filepath
    
    def get_performance_summary(self) -> Dict[str, float]:
        """Get a summary of overall performance"""
        if not self.performance_history:
            return {}
        
        total_pl = sum(m.profit_loss for m in self.performance_history)
        total_trades = sum(m.trades_count for m in self.performance_history)
        avg_win_rate = sum(m.win_rate for m in self.performance_history) / len(self.performance_history)
        max_return = max(m.total_return for m in self.performance_history)
        min_return = min(m.total_return for m in self.performance_history)
        max_drawdown = min(m.max_drawdown for m in self.performance_history)
        
        return {
            'total_profit_loss': total_pl,
            'total_trades': total_trades,
            'average_win_rate': avg_win_rate,
            'maximum_return': max_return,
            'minimum_return': min_return,
            'maximum_drawdown': max_drawdown,
            'days_tracked': len(set(m.timestamp.date() for m in self.performance_history))
        }