#!/bin/bash
# register_crons.sh - Register cron jobs for trading agents

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " OpenClaw Trading Agents - Register Cron Jobs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

PROJECT_PATH="/Users/nunamzza/projects/trading/openclaw-trading-agents"

echo "📋 Cron Jobs to Register:"
echo ""
echo "1. scan-market (Every 5 minutes)"
echo "   Scanner + Sentiment agents run in parallel"
echo ""
echo "2. strategy-review (Every 15 minutes)"
echo "   Strategy agent reviews signals"
echo ""
echo "3. hourly-review (Every hour)"
echo "   Full system review"
echo ""
echo "4. daily-report (23:00 daily)"
echo "   Learning agent generates daily P&L report"
echo ""
echo "5. weekly-optimize (09:00 Sunday)"
echo "   Strategy optimization"
echo ""

# Show OpenClaw cron registration commands
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Registration Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands to register cron jobs:"
echo ""
echo "# 1. Scan Market (Every 5 min)"
echo "openclaw cron create scan-market \\"
echo "  --schedule '*/5 * * * *' \\"
echo "  --message 'Run Scanner + Sentiment Agents (parallel)'"
echo ""
echo "# 2. Strategy Review (Every 15 min)"
echo "openclaw cron create strategy-review \\"
echo "  --schedule '*/15 * * * *' \\"
echo "  --message 'Run Strategy Agent: review signals'"
echo ""
echo "# 3. Hourly Review"
echo "openclaw cron create hourly-review \\"
echo "  --schedule '0 * * * *' \\"
echo "  --message 'Run all agents: hourly system review'"
echo ""
echo "# 4. Daily Report (23:00 Bangkok time)"
echo "openclaw cron create daily-report \\"
echo "  --schedule '0 23 * * *' \\"
echo "  --message 'Run Learning Agent: generate daily performance report'"
echo ""
echo "# 5. Weekly Optimization (Sunday 09:00)"
echo "openclaw cron create weekly-optimize \\"
echo "  --schedule '0 9 * * 0' \\"
echo "  --message 'Run Strategy + Learning: optimize parameters'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Note"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Cron jobs should be registered via OpenClaw gateway."
echo "All times are in Asia/Bangkok timezone."
echo ""
echo "To view registered crons:"
echo "  openclaw cron list"
echo ""
echo "To remove a cron:"
echo "  openclaw cron remove <cron-name>"
echo ""
